name: hotel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  flutter_svg: ^2.0.7
  masked_text: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
      - assets/
      - assets/paid_for.svg
      - assets/paid_for.png
  uses-material-design: true
